#!/usr/bin/env python

def getCampaignNames():
	names = {}
	names['ad'] = 'Andorra'
	names['at'] = 'Austria'
	names['be-bru'] = 'Belgium (Brussels)'
	names['be-vlg'] = 'Belgium (Flanders)'
	names['be-wal'] = 'Belgium (Wallonia)'
	names['by'] = 'Belarus'
	names['ch'] = 'Switzerland'
	names['de-by'] = 'Germany (Bavaria)'
	names['de-he'] = 'Germany (Hesse)'
	names['de-nrw-bm'] = 'Germany (nrw-bm)'
	names['de-nrw-k'] = 'Germany (nrw-k)'
	names['dk-bygning'] = 'Denmark (bygning)'
	names['dk-fortids'] = 'Denmark (fortids)'
	names['ee'] = 'Estonia'
	names['es'] = 'Spain'
	names['es-ct'] = 'Spain (Catalonia)'
	names['es-vc'] = 'Spain (Valencia)'
	names['fr'] = 'France'
	names['ie'] = 'Ireland'
	names['it-88'] = 'Italy (88)'
	names['it-bz'] = 'Italy (bz)'
	names['lu'] = 'Luxemburg'
	names['mt'] = 'Malta'
	names['nl'] = 'Netherlands'
	names['no'] = 'Norway'
	names['pl'] = 'Poland'
	names['pt'] = 'Portugal'
	names['ro'] = 'Romania'
	names['se'] = 'Sweden'
	names['sk'] = 'Slovakia'
	names['us'] = 'United States'
	names['pa'] = 'Panama'
	names['us-ca'] = 'California, United States'
	names['cl'] = 'Chile'
	names['rs'] = 'Serbia'
	names['il'] = 'Israel'
	names['ca'] = 'Canada'
	names['in'] = 'India'
	names['gh'] = 'Ghana'
	names['ar'] = 'Argentina'
	names['mx'] = 'Mexico'
	names['co'] = 'Colombia'
	names['cz'] = 'Czech Republic'
	return names